---
title: "ANALYSIS"
author: "Maxi Ahl"
date: "2025-12-17"
output: html_document
---

```{r, silent=TRUE}
library(terra)      # Reading and manipulating raster data
library(sf)         # Reading and manipulating vector data
library(dplyr)      # Manipulating data.frames
library(ggplot2)    # Visualization
library(spatstat)   # Point Pattern Analysis
library(ggplot2)    # data visualizatio
library(tidyr)      # data wrangling package: change from wide to long format
library(dplyr)      # data manipulation: mutate
library(gridExtra)  # plot multiple ggplot graphs
library(caret)      # cross-validation
library(mapview)    # Map visualization
library(gstat)      # geostatistics
library(stars)      # spatial-temporal data
library(abind)
library(spdep)      # Diagnosing spatial dependence
library(spatialreg) # Spatial lag and spatial error model
library(readxl)
library(raster)
library(ggcorrplot)
library(reshape2)
library(pracma)
library(data.table)
```

```{r}
gisd <- read.csv("/Users/maxi_161/Desktop/UNI/Master/THESIS/DATEN + GIS/SOCIOECONOMIC.nosync/GISD_Bund_Gemeinde.csv", encoding = "UTF-8")

gisd <- gisd %>%
  mutate(gemeinde_id = sprintf("%08s", gemeinde_id))
```

```{r}
str(gisd)
```

```{r}
summary(gisd$year)
```

```{r}

```

```{r}
gisd_latest <- gisd %>%
  arrange(gemeinde_id, desc(year)) %>%
  group_by(gemeinde_id) %>%
  slice(1) %>%
  ungroup()
```

```{r}
gisd_latest
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
